services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    networks:
      - sign_net

  api_gloss:
    build: 
      context: ./gloss_recognition/api
    container_name: api_gloss
    volumes:
      - ./gloss_recognition/MP_DATA_EMBEDDINGS:/app/MP_DATA_EMBEDDINGS:z
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=gloss
      - MODEL_PATH=final_lstm_encoder.keras
      - DATA_PATH=MP_DATA_EMBEDDINGS
      - SELECTED_GLOSS=hello,thank,you,yes,no,home,love
    depends_on:
      - qdrant

    restart: unless-stopped
    networks:
      - sign_net

networks:
  sign_net:
    driver: bridge
